### ISSUE TITLE
请问能分享一下yfcc100m的数据集源文件吗？

### ISSUE THREAD

**Issue by jokelate11** [yiyishiwo/GeoHITS#1]
大神您好！我是武汉大学地信系的学生，想用YFCC100m的数据做一下分析，但是雅虎把这个数据集好像已经关了，网上下载不到了，请问您那里还有数据的源文件吗？如果可以共享的话，不胜感激！如果可以的话，能留个qq吗，我加您。（或者您加我也可以，QQ:594714928）   非常感谢！！

**Comment by woshihuangshuai** [comment]
https://opendata.pku.edu.cn/dataset.xhtml?persistentId=doi:10.18170/DVN/ZM7N9P

**Comment by jokelate11** [comment]
非常感谢！
